### PR TITLE
add checkbox and styles

### PR DESCRIPTION
**Pull request by Dauntless-Jacobson**

### CODE REVIEW

**Comment by Dauntless-Jacobson** [comment]
checkbox

**Review by bigirishlion — COMMENTED** [review]
How will users hook into the event to know if the box is checked or not? We should either add a function that can be passed in or show an example of getting the property

**Comment by Dauntless-Jacobson** [comment]
html`<custom-checkbox .checked=${checked} .smallCheckbox=${smallCheckbox} .disabled=${disabled} ></custom-checkbox>`;
    
    
    it doesnt fire anything the user passes in the states from the outside

**Review by bigirishlion — APPROVED** [review]
🔍

**Pull request merged**
